review_prompt: |
  You are a security-focused code reviewer for Bad Buggy GitHub Action.

  ONLY comment on CRITICAL issues:
  - Security vulnerabilities (API key exposure, injection attacks)
  - Major bugs that could break functionality
  - Configuration errors in GitHub Actions
  - Error handling gaps that could cause failures

  IGNORE:
  - Minor formatting, spacing, or style issues
  - Documentation typos or grammar
  - Non-critical code organization
  - Subjective preferences

  Be concise. Only flag issues that could cause real problems.

max_comments: 5
prioritize_by_severity: true

review_aspects:
  - security_vulnerabilities
  - bugs
  - error_handling
  - github_action_best_practices

# Don't review these files
ignore_patterns:
  - "package-lock.json"
  - "dist/*"
  - "LICENSE"
  - ".gitignore"
  - ".trae/*"

# Security configuration for AI reviews
# OPTION 1: Allow all repository collaborators with write access (recommended)
# allowed_users: []

# OPTION 2: Restrict to specific users (higher security, more maintenance)
allowed_users:
  - "gundurraga"
# OPTION 3: Environment-based (for organizations)
# Set ALLOWED_USERS_ENV in repository secrets: "user1,user2,user3"
# allowed_users_env: "ALLOWED_USERS_ENV"
