review_prompt: |
  You are reviewing 🐰 Bad Buggy - an AI code review GitHub Action.
  This is meta: an AI reviewer reviewing an AI reviewer!

  Focus on:
  - JavaScript best practices and potential bugs
  - GitHub Action specific issues
  - Security concerns (especially API key handling)
  - Error handling and edge cases
  - Code clarity and maintainability

max_comments: 5
prioritize_by_severity: true

review_aspects:
  - bugs
  - security_vulnerabilities
  - error_handling
  - code_quality
  - github_action_best_practices

# Don't review these files
ignore_patterns:
  - "package-lock.json"
  - "dist/*"
  - "LICENSE"
  - ".gitignore"

# Security configuration for AI reviews
# OPTION 1: Allow all repository collaborators with write access (recommended)
# allowed_users: []

# OPTION 2: Restrict to specific users (higher security, more maintenance)
allowed_users:
  - "gundurraga"
# OPTION 3: Environment-based (for organizations)
# Set ALLOWED_USERS_ENV in repository secrets: "user1,user2,user3"
# allowed_users_env: "ALLOWED_USERS_ENV"
