name: 🐰⚡ Bad Buggy reviews itself

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  bad-buggy:
    runs-on: ubuntu-latest

    # Only run on PRs to this repo (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bad Buggy
        uses: gundurraga/bad-buggy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ai-provider: "openrouter"
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          model: "openai/gpt-5-chat"
